services:
  backend:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  configurator:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: "no"
    entrypoint: [ "bash", "-c" ]
    command:
      - >
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: "no"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint: [ "bash", "-c" ]
    command:
      - >
        wait-for-it -t 120 db:3306; wait-for-it -t 120 redis-cache:6379; wait-for-it -t 120 redis-queue:6379; export start=`date +%s`; until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] &&
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] &&
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done; echo "sites/common_site_config.json found"; bench new-site --mariadb-root-password=SecureRootPassword456! --admin-password=admin123 --install-app erpnext --install-app payments --install-app hrms --install-app healthcare --install-app telephony --install-app helpdesk --install-app zatca_erpgulf --install-app telehealth_platform frontend || true;

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=SecureRootPassword456!
      interval: 1s
      retries: 15
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "SecureRootPassword456!"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: on-failure
    command: [ "nginx-entrypoint.sh" ]
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-long:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: on-failure
    command: [ "bench", "worker", "--queue", "long,default,short" ]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-cache:
    image: redis:6.2-alpine
    restart: on-failure
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    restart: on-failure
    volumes:
      - redis-queue-data:/data

  scheduler:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: on-failure
    command: [ "bench", "schedule" ]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: erpnext-healthcare:${ERPNEXT_VERSION}
    restart: on-failure
    command: [ "node", "/home/frappe/frappe-bench/apps/frappe/socketio.js" ]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  logs:
